openapi: 3.0.3
info:
  title: Trousseau
  description: Сервис для передачи вещей внутри общежития
  version: 0.0.2

servers:
  - url: https://localhost:8080

tags:
  - name: media
    description: API для работы с медиа-данными
  - name: seller
    description: API для работы продавца
  - name: public
    description: общедоступный API
  - name: favourites
    description: API для работы с избранным
  - name: constants
    description: API для работы с публичными константами / словарями
  - name: subscription
    description: API для работы с подписками
  - name: notifications
    description: API для работы с уведомлениями
  - name: auth
    description: API для авторизации

paths:
  /seller/media:
    $ref: "./seller/media.yaml#/endpoints/uploadMedia"

  /seller/items:
    post:
      summary: Создание объявления
      operationId: createSellerItem
      tags:
        - seller
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ItemInfoRequest"
      responses:
        200:
          description: Объявление успешно создано
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
    get:
      summary: Получение списка объявлений
      operationId: getSellerItems
      tags:
        - seller
      responses:
        200:
          description: Успешное получение объявлений
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemListResponse"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /seller/items/{itemId}:
    put:
      summary: Обновление объявления
      operationId: updateSellerItem
      tags:
        - seller
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ItemInfoRequest"
      responses:
        200:
          description: Объявление успешно обновлено
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
    get:
      summary: Получение объявления
      operationId: getSellerItem
      tags:
        - seller
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      responses:
        200:
          description: Объявление успешно найдено
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /seller/items/{itemId}/status:
    put:
      summary: Смена состояния объявления
      operationId: changeSellerItemStatus
      tags:
        - seller
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ChangeStatusRequest"
      responses:
        200:
          description: Статус успешно изменен
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /seller/items/{itemId}/booking:
    get:
      summary: Получение информации о бронировании
      operationId: getItemBookingInfo
      tags:
        - seller
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      responses:
        200:
          description: Успешное получение бронирования
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/BookingDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /public/items:search:
    post:
      summary: Поиск объявлений
      operationId: searchItems
      tags:
        - public
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/SearchInfo"
      responses:
        200:
          description: Успешный поиск объявлений
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemListResponse"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /public/items/{itemId}:
    get:
      summary: Получение объявления
      operationId: getItem
      tags:
        - public
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      responses:
        200:
          description: Объявление успешно найдено
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /public/items/{itemId}/status:
    put:
      summary: Смена состояния объявления
      operationId: changeItemStatus
      tags:
        - public
      parameters:
        - $ref: "./common.yaml#/components/parameters/itemId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ChangeStatusRequest"
      responses:
        200:
          description: Статус успешно изменен
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /public/items/bookings:
    get:
      summary: Получение списка забронированных объявлений
      operationId: getBookedItems
      tags:
        - public
      responses:
        200:
          description: Успешное получение списка бронирований
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ItemListResponse"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"

  /public/items/{itemId}/favourite:
    $ref: "./public/favourites.yaml#/endpoints/changeFavourite"
  /public/items/favourites:
    $ref: "./public/favourites.yaml#/endpoints/getFavourites"

  /public/categories/tree:
    $ref: "./public/constants.yaml#/endpoints/getCategoryTree"

  /public/subscriptions:
    post:
      summary: Создание подписки
      operationId: createSubscription
      tags:
        - subscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/SubscriptionInfoRequest"
      responses:
        200:
          description: Подписка успешно создана
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/SubscriptionDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
    get:
      summary: Получение списка подписок
      operationId: getSubscriptions
      tags:
        - subscription
      responses:
        200:
          description: Успешное получение подписок
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/SubscriptionListResponse"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
  /public/subscriptions/{subscriptionId}:
    put:
      summary: Обновление подписки
      operationId: updateSubscription
      tags:
        - subscription
      parameters:
        - $ref: "./common.yaml#/components/parameters/subscriptionId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/SubscriptionInfoRequest"
      responses:
        200:
          description: Подписка успешно обновлена
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/SubscriptionDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
    delete:
      summary: Удаление подписки
      operationId: deleteSubscription
      tags:
        - subscription
      parameters:
        - $ref: "./common.yaml#/components/parameters/subscriptionId"
      responses:
        200:
          description: Подписка успешно удалена
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ErrorObject"

  /public/notifications:
    $ref: "./public/notifications.yaml#/endpoints/getNotifications"
  /public/notifications/unread/count:
    $ref: "./public/notifications.yaml#/endpoints/getUnreadNotificationsCount"
  /public/notifications/{notificationId}/read:
    $ref: "./public/notifications.yaml#/endpoints/markNotificationRead"
  /public/notifications/token:
    $ref: "./public/notifications.yaml#/endpoints/updateNotificationsToken"

  /auth/signup:
    $ref: "./auth.yaml#/endpoints/signUp"
  /auth/signin:
    $ref: "./auth.yaml#/endpoints/signIn"
  /auth/signout:
    $ref: "./auth.yaml#/endpoints/signOut"
  /auth/profile:
    $ref: "./auth.yaml#/endpoints/getProfileInfo"
