openapi: 3.0.3
info:
  title: Trousseau
  description: Сервис для передачи вещей внутри общежития
  version: 0.0.2
servers:
  - url: https://localhost:8080
components:
  schemas:
    ErrorObject:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        humanMessage:
          type: string
    mediaData:
      type: string
      format: binary
    UploadMediaRequest:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/mediaData"
    mediaId:
      type: string
    UploadMediaResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/mediaId"
    itemTitle:
      type: string
    itemMedia:
      type: array
      items:
        $ref: "#/components/schemas/mediaId"
    itemDescription:
      type: string
    ItemInfoRequest:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/itemTitle"
        media:
          $ref: "#/components/schemas/itemMedia"
        description:
          $ref: "#/components/schemas/itemDescription"
    url:
      type: string
    ItemMediaDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/mediaId"
        href:
          $ref: "#/components/schemas/url"
    mediaDtos:
      type: array
      items:
        $ref: "#/components/schemas/ItemMediaDto"
    itemId:
      type: string
    itemStatus:
      type: string
      enum:
        - DRAFT
        - READY
        - PUBLISHED
        - BOOKED
        - ARCHIVED
    ItemDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/itemId"
        title:
          $ref: "#/components/schemas/itemTitle"
        media:
          $ref: "#/components/schemas/mediaDtos"
        description:
          $ref: "#/components/schemas/itemDescription"
        status:
          $ref: "#/components/schemas/itemStatus"
    GetItemsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemDto"
paths:
  /seller/media:
    post:
      summary: Загрузка медиа-файла
      operationId: uploadMedia
      tags:
        - media
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadMediaRequest"
      responses:
        200:
          description: Медиа-файл успешно загружен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadMediaResponse"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /seller/items:
    post:
      summary: Создание объявления
      operationId: createItem
      tags:
        - item
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInfoRequest"
      responses:
        200:
          description: Объявление успешно создано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    get:
      summary: Получение списка объявлений
      operationId: getItems
      tags:
        - item
      responses:
        200:
          description: Успещное получение объявлений
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetItemsResponse"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /seller/items/{itemId}:
    put:
      summary: Обновление объявления
      operationId: updateItem
      tags:
        - item
      parameters:
        - in: path
          name: itemId
          description: Идентификатор объявления
          required: true
          schema:
            $ref: "#/components/schemas/itemId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInfoRequest"
      responses:
        200:
          description: Объявление успешно обновлено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    get:
      summary: Получение объявления
      operationId: getItem
      tags:
        - item
      parameters:
        - in: path
          name: itemId
          description: Идентификатор объявления
          required: true
          schema:
            $ref: "#/components/schemas/itemId"
      responses:
        200:
          description: Объявление успешно найдено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemDto"
        400:
          description: Неверный формат запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Сервис временно недоступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
